site_name: Teamstudio Documentation

theme:
  name: material
  
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
      
plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: 日本語
          build: true